### Matriz inversa no Python

Comando para obter o determinante de uma matriz é numpy.linalg.inv      

In [7]:
import numpy as np
A = np.array([[6, 1, 1],
             [4, -2, 5],
             [2, 8, 7]])
invA = np.linalg.inv(A)
print(f'''A inversa da matriz A é: 
{invA}''')

A inversa da matriz A é: 
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


Crie uma função em python que calcula a fatoração em primos de um número positivo e inteiro.

In [15]:
def fatores_primos(numero):
    fatores = []
    divisor = 2

    while numero > 1:
        while numero % divisor == 0:
            fatores.append(divisor)
            numero /= divisor
        divisor += 1

    return fatores
fatores_primos(630)
    
        

[2, 3, 3, 5, 7]

In [26]:
def fatora_primo():
    numero = int(input('Digite um número positivo e inteiro: '))
    print(f'Fatorando o número: {numero}')
    fator = 2 # primeiro primo
    while numero != 1:
        # contador para verificar a quantidade de vezes que o fator fou utilizado
        contador = 0
        while numero % fator == 0:
            numero = numero / fator
            contador += 1
        
        # imprime a quantidade de vezes que o fator foi utilizado
        if contador != 0:
            
            print(f'{fator} elevado à {contador}')
        fator = fator + 1

fatora_primo()

Fatorando o número: 440
2 elevado à 3
5 elevado à 1
11 elevado à 1


Fatoração Eigen em Python

Comando para obter o determinante de uma matriz é numpy.linalg.eig()


In [31]:
import numpy as np

a = np.array([[0, 2], 
              [2, 3]])
w, v = np.linalg.eig(a)
print(f'E-value: {w}')
print(f'E-vector: {v}')

E-value: [-1.  4.]
E-vector: [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]
