In [2]:
import numpy as np
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
print(matriz.shape)

print(matriz[1,2])

[[1 2 3]
 [4 5 6]]
(2, 3)
6


Para gerar uma matriz com números aleatórios, pode-se utilizar o comando numpy.random.rand().

In [5]:
# 
import numpy as np

A = np.random.rand(2, 2)
print(f'Matriz A: {A}')

B = np.random.rand(3,4)
print(f'Matriz B: {B}')

Matriz A: [[0.1415601  0.31466921]
 [0.03597508 0.6699072 ]]
Matriz B: [[0.37098278 0.46916189 0.28921157 0.57754215]
 [0.7925774  0.0717068  0.87118654 0.03180176]
 [0.98984204 0.87292836 0.85511797 0.9439297 ]]


Para gerar uma matriz identidade, pode-se utilizar o comando numpy.identity()

In [6]:
import numpy as np
I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Para gerar uma matriz transposta, pode-se utilizar o comando numpy.transpose().

In [17]:
import numpy as np

A = np.random.randint(10, size=(3, 2))

A_transposta = np.transpose(A)

print(f'Matriz: {A}')
print(f'Matriz Transposta: {A_transposta}')

Matriz: [[1 3]
 [9 1]
 [6 2]]
Matriz Transposta: [[1 9 6]
 [3 1 2]]


Comando para multiplicação entre matrizes é numpy.matmul(A, B).

In [18]:
#Exemplo
import numpy as np

A = np.array([[1, -3, 5], [8, 0, 3]])
B = np.array([[2, 4], [6, 10], [1, 5]])

# Multiplicação por uma constante.
multi = np.matmul(A, B)
print(f'''A multiplicação etre matrizes é: 
{multi}''')

A multiplicação etre matrizes é: 
[[-11  -1]
 [ 19  47]]


Comando para obter o determinante de uma matriz é numpy.inalg.det().

In [19]:
import numpy as np
A = np.array([[1 , 9, 5], [3, 7, 8], [10, 4, 2]])

det_A = np.linalg.det(A)

print(f'O determinante da matriz é: {det_A}')

O determinante da matriz é: 358.0


Calcule o determinante das matrizes A e B abaixo utilizando um código em python 

A = [[2, 5, -3], [1, 4, 7], [-2, 0, 6]]

B = [[raiz2, 2, 1], [-1, raiz3, 3], [3, 2, raiz6]] 

In [ ]:
import numpy as np
from math import sqrt

A = np.array([[2,5,-3],[1,4,7],[-2,0,6]])
B = np.array([[sqrt(2),2,1], [-1,sqrt(3),3], [3,2,sqrt(6)]])

detA = np.linalg.det(A)
detB = np.linalg.det(B)

print(f'Determinante de A: {detA}')
print(f'Determinante de B: {detB}')