In [1]:
import numpy as np
import random

In [2]:
#Vetores em R
#Exercicio fácil: Crie um vetor com os númes de 1 a 10 e imprima-o.
vetor = list(range(1,11))
print(vetor)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [3]:
#Exercício fácil: Crie um vetor com os números pares de 2 a 20 e imprima-o.
vetor = list(range(2,21,2))
print(vetor)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [4]:
# Exercício médio: Calcule a soma dos elementos de um vetor com números de 1a 100.
vetor = list(range(1,101))
soma = sum(vetor)
print(soma)

5050


In [10]:
# Exercício médio: Encontre o maior e o menor valor em um vetor de números
# aleatórios entre 1 e 1000, de tamanho 50.
print('Opção 1')
vetor = [random.randint(1,1001) for _ in range(50)]
menor = min(vetor)
maior = max(vetor)
print(f'Maior: {maior}, menor: {menor}')

print('Opção 2')
vetor2 = random.sample(range(1000), 50)
menor2 = min(vetor2)
maior2 = max(vetor2)
print(f'Maior: {maior2}, menor: {menor2}')

print('Opção 3')
vetor_aleatorio = np.random.randint(1, 1001,size = 50)
menor3 = min(vetor_aleatorio)
maior3 = max(vetor_aleatorio)
print(f'Maior: {maior3}, menor: {menor3}')

Opção 1
Maior: 1001, menor: 3
Opção 2
Maior: 997, menor: 19
Opção 3
Maior: 994, menor: 35


In [6]:
# Exercício difícil: Crie um vetor com os 10 primeiros números primos
def eh_primo(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            return False
    return True
primos = []
num = 2
while len(primos) < 10:
    if eh_primo(num):
        primos.append(num)
    num += 1
print(primos)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]


In [7]:
# Exercício difícil: Inverta a ordem dos elementos de um vetor
# de tamanho 20, preenchido com números aleatórios
vetor = [random.randint(1, 100) for _ in range(20)]
print(vetor)

vetor_invertido = vetor[::-1]
print(vetor_invertido)

[26, 42, 87, 31, 87, 54, 96, 15, 80, 71, 78, 16, 30, 20, 3, 17, 71, 17, 68, 76]
[76, 68, 17, 71, 17, 3, 20, 30, 16, 78, 71, 80, 15, 96, 54, 87, 31, 87, 42, 26]


In [8]:
# Matrizes
# Exercício fácil: Crie uma matriz 3x3 com os números de 1 a 9.
matriz = np.arange(1,10).reshape(3, 3)
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
#Exercício fácil: Crie uma matriz identidade 4x4 e imprima-a.
print('Opção 1')
matriz_identidade = np.identity(4)
print(matriz_identidade)

print('Opção 2')
matriz_identidade2 = np.eye(4)
print(matriz_identidade2)

Opção 1
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Opção 2
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
# Exercício médio: Some duas matrizes 2x2.
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])
matriz_soma = matriz1 + matriz2
print(matriz_soma)

[[ 6  8]
 [10 12]]


In [14]:
# Exercício médio: Multiplique duas matrizes 2x2.
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])
matriz_mult = np.dot(matriz1, matriz2)
print(matriz_mult)

[[19 22]
 [43 50]]


In [15]:
# Exercício difícil: Calcule a transposta de uma matrix 3x3.
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz_transposta = np.transpose(matriz)
print(matriz_transposta)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [16]:
# Exercício difícil: Calcule a determinante de uma matriz 3x3.
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
determinante = np.linalg.det(matriz)
print(determinante)

0.0


In [5]:
# Exercício fácil: Crie um vetor de categorias (fatores) com as cores 'vermelho', 'Azul' e 'Verde'
import pandas as pd
cores = pd.Categorical(['vermelho', 'azul', 'Verde'])
print(cores)

['vermelho', 'azul', 'Verde']
Categories (3, object): ['Verde', 'azul', 'vermelho']


In [8]:
import pandas as pd
# Exercício fácil: Crie um vetor de fatores para os dias da semana e imprima-os.
dias_da_semana = pd.Categorical(['Segunda', 'Terca', 'Quarta', 'Quinta', 'Sexta', 'Sabado', 'Domingo'])
print(dias_da_semana)

['Segunda', 'Terca', 'Quarta', 'Quinta', 'Sexta', 'Sabado', 'Domingo']
Categories (7, object): ['Domingo', 'Quarta', 'Quinta', 'Sabado', 'Segunda', 'Sexta', 'Terca']


In [10]:
# Exercício médio: Crie um vetor de fatores com as categorias 'Baixo', 'mádio' e 'alto' e ordene-os.
niveis = pd.Categorical(['Baixo', 'Alto', 'Médio'], categories = ['Baixo', 'Médio', 'Alto'], ordered=True)
print(niveis)

['Baixo', 'Alto', 'Médio']
Categories (3, object): ['Baixo' < 'Médio' < 'Alto']


In [12]:
# Exercício médio: Converta um vetor de fatores em um vetor numérico.
import pandas as pd
categorias = pd.Categorical(['Baixo', 'Alto', 'Médio'], categories = ['Baixo', 'Médio', 'Alto'], ordered=True)
numeros = categorias.codes
print(numeros)

[0 2 1]


In [15]:
# Exercício difícil: Crie um vetor de fatores com as categorias
# 'Pequeno', 'Médio' e 'Grande' e substitua pequeno por 'Extra Pequeno'.
import pandas as pd
tamanhos = pd.Categorical(['Pequeno', 'Médio', 'Grande'], categories = ['Pequeno', 'Médio', 'Grande'], ordered=True)
tamanhos2 = tamanhos.rename_categories({'Pequeno': 'Extra Pequeno'})
print(tamanhos2)

['Extra Pequeno', 'Médio', 'Grande']
Categories (3, object): ['Extra Pequeno' < 'Médio' < 'Grande']


In [22]:
# Exercício difícil: Crie um vetor de fatores com 100 elementos aleatórios entre
# 'Baixo', 'Médio', 'Alto', e calcule a frequência de cada categoria.
import pandas as pd
import random
categorias = ['Baixo', 'Médio', 'Alto']
vetor = [random.choice(categorias) for _ in range(100)]
fatores = pd.Categorical(vetor, categories = categorias, ordered=True)
frequencias = pd.value_counts(fatores)
print(frequencias)

Baixo    37
Médio    34
Alto     29
Name: count, dtype: int64


C:\Users\84284528572\AppData\Local\Temp\ipykernel_3216\2174898043.py:8: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  frequencias = pd.value_counts(fatores)
